### PR TITLE
Scroll page

### PR DESCRIPTION
**Pull request by JakeSidSmith**
Allow scrolling the page when using touch devices (unless hold time is 0).

Relies on #54

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
@adsteel Could you pull this branch into your project & test the scrolling. I think this should fix #51 and possibly others. :)

**Comment by JakeSidSmith** [comment]
Note:

You'll have to add the following css to the body, or reorderable list component.

```
-webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
-webkit-tap-highlight-color: transparent;
```

**Comment by adsteel** [comment]
@JakeSidSmith So I replaced my lib JS reorderable file with the new index.js from this PR, updated names etc and then added those classes to `body`. Everything works the same on desktop, but still fails to scroll on iPad.

**Comment by JakeSidSmith** [comment]
@adsteel Are you certain your code has rebuilt correctly / is linked to this exact copy of react-reorder? I've tested this on several iPhones & it works fine.

**Comment by adsteel** [comment]
@JakeSidSmith I'm not sure, no. Pretty sure, but I'll do it again tomorrow morning.

**Comment by JakeSidSmith** [comment]
Might be worth trying the following:

1. Ensure all cache is cleared
2. Run the examples locally & access from your iPad

**Comment by JakeSidSmith** [comment]
@adsteel I've just had a chance to test this out on an iPad at work.

Works with react-reorder (but is a little crappy).

You can scroll the body, but the inner scrollable element must already be at the very top / bottom of it's scrollable area, and then you have to take your finger off and drag again.

Decided to try another example with plain html, that has a scrollable div inside a scrollable body. Works exactly the same.

I think unfortunately iPad support for nested scrollable elements is pretty poor.

**Comment by adsteel** [comment]
@JakeSidSmith Curse you, iPad! I guess that's the price to be paid for being on the cutting edge. I still think this is a great library, and we'll keep using it with. Thanks for the good work, and let me know if there's any other way I can help.

**Comment by JakeSidSmith** [comment]
@adsteel Just to confirm, this does solve the scrolling issue, but it's a bit crappy? If it works then I'll merge, as this is a vast improvement on the previous version.

**Comment by ekonstantinidis** [comment]
:ship:

**Comment by adsteel** [comment]
@JakeSidSmith I'm not sure if this fixes other scrolling issues, but version 1.3 has broken my scrolling solution for the prior version (a scrolling div within the document). ie My scrollable div does not scroll with version 1.3.

**Pull request merged**
