### PR TITLE
Fix window undefined on server

### PR DESCRIPTION
**Pull request by HriBB**

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
That is an interesting workaround... XD

Unfortunately I think this will cause some issues if for some reason `window` and `this` are undefined, as it'll then try to assign properties to `undefined`.

I'm still unsure how window can be undefined...

**Comment by JakeSidSmith** [comment]
Something like this seems a little safer: https://github.com/facebook/react/blob/092f5ae867721bdc386120a14f789d0a64d31916/docs/js/react-dom.js

**Comment by HriBB** [comment]
Argh my head hurts from all these bundlers and configurations and whatnot :)

Yeah FB uses this [template](https://github.com/ForbesLindesay/umd/blob/master/template.js) and I guess so should we.

I guess in node, `window` is undefined when you are in server environment. I can try and fix this by using this template, but I'm not sure how to test it properly. What if we added some tests?

**Comment by JakeSidSmith** [comment]
Tests would be good, but I think I'm going to save that until after the rework. :)

**Comment by JakeSidSmith** [comment]
Could you try it like this? If it works ok, I'll merge your branch (and update my other repos). :)

https://github.com/JakeSidSmith/canvasimo/blob/bc01196d6510b8634fcde27081fa9337b000e645/lib/index.js#L1019

**Comment by HriBB** [comment]
Sure. I need to test it first, so it might take a few days. I have done some reading and now I know that my initial workaround will not work :)

**Comment by HriBB** [comment]
@JakeSidSmith I fixed the export following the `Canvasimo` example. I built and ran the examples afterwards and it works. I also did a `npm link` into my project that uses `react-reorder` and server rendering now works.

I am still not sure about the global export. Before you checked for the existence of `React` and `ReactDOM` on the `root` object, which I don't. 

Anyway, please review and let me know if it's OK.

**Comment by JakeSidSmith** [comment]
The global export should be fine. If React or ReactDOM aren't available that's the developers fault. XD Or that they do not support being used globally.

Looks good to me! ✨

**Pull request merged**
