### PR TITLE
Create class warning (fix)

### LINKED ISSUE #79: Warning with react 15.5.0
Warning: Reorder: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### PR DESCRIPTION
**Pull request by JakeSidSmith**
Fixes #79

### CODE REVIEW

**Comment by romamatusevich** [comment]
The changes look fine. I don't think this pull request needs some changes in gitignore, but it's not an issue.
```
/coverage/**
.nyc_output/*
```

Tested building and examples locally. Also the result is fine without react 15.5.0 warning.

**Comment by JakeSidSmith** [comment]
@romamatusevich since adding coverage to the v3 alpha, I figured it was easier for me to update the gitignore in v2 than to keep deleting all the output files. Shouldn't have any impact on the lib itself. :)

**Comment by JakeSidSmith** [comment]
If you're happy I'll merge it now.

**Comment by romamatusevich** [comment]
Thank you!

**Comment by wmertens** [comment]
Why not simply convert it to a ES6 class instead of using that create-class library? Is there some blocking dependency?

**Comment by JakeSidSmith** [comment]
ES6 classes work pretty differently, e.g. not binding methods. This was the quickest way to get a fix out. Otherwise I'd not only have to re-write the component, but setup all the build / dist stuff to work with ES6. Will likely be rewriting in TypeScript in the near future.

**Comment by wmertens** [comment]
Aha makes sense :+1:

**Pull request merged**
